[package]
name = "harvest-benchmark"
version = "0.1.0"
edition = "2021"
description = "Runs a set of benchmarks and provides useful output"
license = "MIT OR Apache-2.0"

[[bin]]
name = "benchmark"
path = "src/main.rs"


[dependencies]
harvest_ir = { workspace = true }
harvest_translate = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.0"
csv = "1.3"
regex = "1.12.2"
wait-timeout = "0.2"
log = "0.4.28"
