[package]
name = "identify_project_kind"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
harvest_ir.workspace = true
load_raw_source = { version = "0.1.0", path = "../load_raw_source" }

[lints]
workspace = true
