[workspace]
members = [ "ir","translate", "benchmark"]
resolver = "3"

[workspace.dependencies]
harvest_ir = { path = "ir" }
harvest_translate = { path = "translate" }
tempfile = "3.23.0"
thiserror = "2.0.17"

[workspace.lints.clippy]
self_named_module_files = "warn"
